project:
  type: book
  output-dir: docs

book:
  downloads: [pdf]
  title: "Principles and recommendations"
  page-navigation: true
  page-footer:
    left: |
      *Principles and Recommendations for Population and Housing Censuses*.
  search:
    location: navbar
    type: textbox
  reader-mode: true

  chapters:
    - index.qmd
    - part1.qmd
    - part2.qmd
    - part3.qmd
    - part4.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: lumen
      dark: darkly
    css: custom.css
  pdf:
    documentclass: scrreprt

fig-cap-location: top
crossref:
  fig-title: Table
  title-delim: .
  fig-prefix: Table
  
editor: visual

